### ISSUE TITLE
the `limit` setting needs to find its way into the /search app 

### ISSUE THREAD

**Issue by bradnoble** [ibm-cds-labs/simple-search-service#10]
... it shouldn't have to be set on API calls.

So, the app needs to change, and requests out to /search should _no longer_ be appended with the limit query param.

**Comment by vabarbosa** [comment]
[fix committed](https://github.com/ibm-cds-labs/simple-search-service/commit/b38aaa9fb2450b4991df260308638c01a6aa1f21)
