### ISSUE TITLE
Typo in Search Tips

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/simple-search-service#15]
![search_tips_typo](https://cloud.githubusercontent.com/assets/12279008/11941155/938c7fd0-a7fb-11e5-826d-00ce8b4f42ce.png)

missing ' character in search tips (see screen shot). But query works anyway.

**Comment by vabarbosa** [comment]
change delivered

**Comment by jessmantaro** [comment]
Va, you are _fast_!
