### ISSUE TITLE
trouble uploading data

### ISSUE THREAD

**Issue by bradnoble** [ibm-cds-labs/simple-search-service#42]
When a user is uploading data, we show them the preview of the data that's about to get indexed, but we don't allow them to "go back" and upload again. Poses a problem when, for example, a user is trying to upload/index a CSV with a poorly formatted header row.

Requires a hard refresh of the app to resolve.

**Comment by glynnbird** [comment]
I think this is a UI thing @vabarbosa. couchimport has the preview operation which allows the front end to render the field names. If the user decides not to do the import, how do they go "back" to the start of the workflow? I think that's what is at the heart of this ticket.

**Comment by vabarbosa** [comment]
alright, thx

**Comment by vabarbosa** [comment]
@bradnoble https://github.com/ibm-cds-labs/simple-search-service/pull/43
the ui should now allow you to go back and re-upload as long as you havent imported/created index.
Glynn will investigate what basic checks could be done with couchimport.

**Comment by bradnoble** [comment]
merged

**Comment by glynnbird** [comment]
couchimport 0.4.0 allows SSS to determine during preview whether a file is 

- tab delimited
- comma delimited
- something else (probably not worth proceeding with)
