### ISSUE TITLE
Lockdown mode

### ISSUE THREAD

**Issue by glynnbird** [ibm-cds-labs/simple-search-service#8]
If an environment variable LOCKDOWN is present and set to "true", then UI should not allow data to be deleted or added. SSS would just behave as a search API.

**Comment by Rio517** [comment]
Are you familiar with any workarounds that might help me secure the data in our SSS instance on bluemix?  I just need a simple endpoint to search 5.7 million records.   SSS is prefect, but it would be if I could even just limit access to certain hosts or IP ranges, or make the cloudant backend read only somehow.  Thanks!

**Comment by glynnbird** [comment]
@Rio517 Thanks for the feedback. I've added lockdown mode to this app. Simply create an environment variable `LOCKDOWN` and set it to `true` to disable the UI but let the search functionality continue.

**Comment by Rio517** [comment]
Great!  thanks!
